local Remap = require("sjdonado.keymap")
local nnoremap = Remap.nnoremap

nnoremap("<C-p>", ":Telescope")

nnoremap("<leader>ps", function()
  require('telescope.builtin').grep_string({ search = vim.fn.input("Grep For > ")})
end)
nnoremap("<leader>pd", function()
  require('sjdonado.telescope').search_dotfiles({ hidden = true })
end)
nnoremap("<Leader>pf", function()
  require('telescope.builtin').find_files()
end)
nnoremap("<leader>pw", function()
  require('telescope.builtin').grep_string { search = vim.fn.expand("<cword>") }
end)
nnoremap("<leader>pb", function()
  require('telescope.builtin').buffers()
end)
nnoremap("<leader>pr", function()
  require('telescope.builtin').resume()
end)
nnoremap("<leader>po", function()
  require('telescope.builtin').oldfiles()
end)
nnoremap("<leader>pk", function()
  require('telescope.builtin').keymaps()
end)

nnoremap("<leader>vh", function()
  require('telescope.builtin').help_tags()
end)

nnoremap("<leader>dr", function()
  require('telescope').extensions.dap.configurations()
end)
nnoremap("<leader>dc", function()
  require('telescope').extensions.dap.commands()
end)

nnoremap("<leader>gf", function()
  require('telescope.builtin').git_files()
end)

nnoremap("<leader>gc", function()
  require('telescope.builtin').git_commits()
end)
nnoremap("<leader>gb", function()
  require('telescope.builtin').git_branches()
end)
