live_config_reload = true

import = [
  "~/.config/alacritty/themes/dark.toml"
]

[colors]
draw_bold_text_with_bright_colors = true

[env]
COLORTERM = "truecolor"
TERM = "xterm-256color"

[font]
size = 13

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[font.normal]
family = "Hack Nerd Font"

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "CreateNewWindow"

[mouse]
hide_when_typing = true

[scrolling]
history = 0

[selection]
save_to_clipboard = false

[window]
# decorations = "none"
# startup_mode = "Maximized"
