[terminal]
osc52 = "CopyPaste"

[colors]
draw_bold_text_with_bright_colors = true

[env]
COLORTERM = "truecolor"
TERM = "xterm-256color"

[font]
size = 12.5

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[font.normal]
family = "Menlo"

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "CreateNewWindow"

[[keyboard.bindings]]
key = "Z"
mods = "Control"
action = "None"

[mouse]
hide_when_typing = true

[scrolling]
history = 0

[selection]
save_to_clipboard = false

[window]
decorations = "None"
startup_mode = "Maximized"

[general]
live_config_reload = true

import = ["/Users/juan/.config/alacritty/themes/light.toml"]
