live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#676965"
blue = "#83afd8"
cyan = "#37e5e7"
green = "#98e342"
magenta = "#bc93b6"
red = "#f44135"
white = "#f1f1ef"
yellow = "#fcea60"

[colors.cursor]
cursor = "#fffeff"
text = "#000000"

[colors.normal]
black = "#000000"
blue = "#417ab3"
cyan = "#00a7aa"
green = "#5da602"
magenta = "#88658d"
red = "#d71e00"
white = "#dbded8"
yellow = "#cfad00"

[colors.primary]
background = "#000000"
foreground = "#fffeff"

[colors.selection]
background = "#c1ddff"
text = "#000000"

[env]
COLORTERM = "truecolor"
TERM = "xterm-256color"

[font]
size = 13

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "CreateNewWindow"

[mouse]
hide_when_typing = true

[scrolling]
history = 0

[selection]
save_to_clipboard = false

[window]
decorations = "none"
startup_mode = "Maximized"
