[[keymaps]]
command = "PageSelectNextOrScrollDown"
key_sequence = "C-e"

[[keymaps]]
command = "PageSelectPreviousOrScrollUp"
key_sequence = "C-y"

[[keymaps]]
command = "Quit"
key_sequence = "g q"

[[keymaps]]
command = "None"
key_sequence = "q"

[[keymaps]]
command = "None"
key_sequence = "C-f"

[[keymaps]]
command = "None"
key_sequence = "C-b"
