[colors.primary]
background = "#f8f9fa"
foreground = "#2e323a"

[colors.normal]
black = "#3a3f45"
red = "#e03b3b"
green = "#138a41"
yellow = "#d39d00"
blue = "#1a73e8"
magenta = "#9b4ef9"
cyan = "#1ca5a5"
white = "#87939f"

[colors.bright]
black = "#4a515a"
red = "#d12038"
green = "#20a063"
yellow = "#c88801"
blue = "#3498ff"
magenta = "#a56fff"
cyan = "#26bfbf"
white = "#adb5bd"

[colors.cursor]
cursor = "#2e323a"
text = "#f8f9fa"

[colors.selection]
background = "#d0e7ff"
text = "#1e1e1e"
