gui:
  windowSize: 'normal' # one of 'normal' | 'half' | 'full' default is 'normal'
  scrollHeight: 4 # how many lines you scroll by
  expandFocusedSidePanel: true
  mainPanelSplitMode: 'vertical'
  nerdFontsVersion: "3"
  theme:
    optionsTextColor:
      - default
      - bold
    selectedLineBgColor:
      - default
      - bold
    selectedRangeBgColor:
      - default
      - bold
git:
  paging:
    colorArg: always
    pager: delta --paging=never
  diffContextSize: 6
os:
  openCommand: nvr -l {{filename}}
  editCommand: nvr -l {{filename}}
keybinding:
  universal:
    quit-alt1: ''
    scrollUpMain: '<c-y>'
    scrollDownMain: '<c-e>'
    # scrollLeft: '<c-h>'
    # scrollRight: '<c-l>'
  branches:
    copyPullRequestURL: 'Y'
  commits:
    copyCommitMessageToClipboard: 'Y'
