gui:
  portraitMode: "always"
  expandFocusedSidePanel: true
  mainPanelSplitMode: vertical
  showCommandLog: false
git:
  pagers:
    - colorArg: always
      pager: delta-themed
os:
  editPreset: nvim-remote
keybinding:
  universal:
    edit: [e, o]
    openFile: O
