local inoremap = require("sjdonado.keymap").inoremap

inoremap("<C-c><CR>", function()
	require("copilot.suggestion").accept()
end)
inoremap("<C-c>w", function()
	require("copilot.suggestion").accept_word()
end)
inoremap("<C-c>l", function()
	require("copilot.suggestion").accept_line()
end)
inoremap("<C-c>n", function()
	require("copilot.suggestion").next()
end)
inoremap("<C-c>p", function()
	require("copilot.suggestion").prev()
end)
inoremap("<C-c>x", function()
	require("copilot.suggestion").dismiss()
end)
inoremap("<C-c>t", function()
	require("copilot.suggestion").toggle_auto_trigger()
end)
