local inoremap = require("sjdonado.keymap").inoremap

inoremap("<C-p><CR>", function()
  require("copilot.suggestion").accept()
end)
inoremap("<C-p>w", function()
  require("copilot.suggestion").accept_word()
end)
inoremap("<C-p>l", function()
  require("copilot.suggestion").accept_line()
end)
inoremap("<C-p>n", function()
  require("copilot.suggestion").next()
end)
inoremap("<C-p>p", function()
  require("copilot.suggestion").prev()
end)
inoremap("<C-p>x", function()
  require("copilot.suggestion").dismiss()
end)
inoremap("<C-p>t", function()
  require("copilot.suggestion").toggle_auto_trigger()
end)
