local nnoremap = require("sjdonado.keymap").nnoremap

nnoremap("<C-p>", ":Telescope")

nnoremap("<leader>ps", function()
  require("telescope.builtin").grep_string({ search = vim.fn.input("Grep For > ") })
end)
nnoremap("<leader>pd", function()
  require("sjdonado.telescope").search_dotfiles()
end)
nnoremap("<leader>pf", function()
  require("telescope.builtin").find_files()
end)
nnoremap("<leader>pw", function()
  require("telescope.builtin").grep_string({ search = vim.fn.expand("<cword>") })
end)
nnoremap("<leader>pb", function()
  require("sjdonado.telescope").buffers()
end)
nnoremap("<leader>pr", function()
  require("telescope.builtin").lsp_references()
end)
nnoremap("<leader>po", function()
  require("telescope.builtin").oldfiles()
end)
nnoremap("<leader>pp", function()
  require("telescope.builtin").resume()
end)

nnoremap("<leader>sk", function()
  require("telescope.builtin").keymaps()
end)
nnoremap("<leader>st", function()
  require("telescope.builtin").help_tags()
end)
nnoremap("<leader>sm", function()
  require("telescope.builtin").man_pages()
end)
nnoremap("<leader>sH", function()
  require("telescope.builtin").highlights()
end)

nnoremap("<leader>ch", function()
  require("telescope.builtin").command_history()
end)
nnoremap("<leader>sh", function()
  require("telescope.builtin").search_history()
end)

nnoremap("<leader>dr", function()
  require("telescope").extensions.dap.configurations()
end)
nnoremap("<leader>dc", function()
  require("telescope").extensions.dap.commands()
end)
nnoremap("<leader>dlb", function()
  require("telescope").extensions.dap.list_breakpoints()
end)
