local nnoremap = require("sjdonado.keymap").nnoremap

local custom_pickers = require("sjdonado.telescope")

nnoremap("<leader>ps", function()
  custom_pickers.live_grep()
end)
nnoremap("<leader>pg", function()
  custom_pickers.grep_string({ search = vim.fn.input("Grep For > ") })
end)
nnoremap("<leader>pf", function()
  custom_pickers.find_files()
end)
nnoremap("<leader>pw", function()
  custom_pickers.grep_string({ search = vim.fn.expand("<cword>") })
end)
nnoremap("<leader>pb", function()
  custom_pickers.buffers()
end)
nnoremap("<leader>pa", function()
  custom_pickers.find_all()
end)
nnoremap("<leader>pr", function()
  custom_pickers.live_grep_all_files()
end)
nnoremap("<leader>po", function()
  require("telescope.builtin").oldfiles()
end)
nnoremap("<leader>pp", function()
  require("telescope.builtin").resume()
end)

nnoremap("<leader>pk", function()
  require("telescope.builtin").keymaps()
end)
nnoremap("<leader>pt", function()
  require("telescope.builtin").help_tags()
end)
nnoremap("<leader>pm", function()
  require("telescope.builtin").man_pages()
end)

nnoremap("<leader>pc", function()
  require("telescope.builtin").command_history()
end)
nnoremap("<leader>ph", function()
  require("telescope.builtin").search_history()
end)

-- git
nnoremap("<leader>gc", function()
  require("telescope.builtin").git_commits()
end)
nnoremap("<leader>gb", function()
  require("telescope.builtin").git_branches()
end)
nnoremap("<leader>gs", function()
  require("telescope.builtin").git_stash()
end)

-- dap
nnoremap("<leader>dr", function()
  require("telescope").extensions.dap.configurations()
end)
nnoremap("<leader>dc", function()
  require("telescope").extensions.dap.commands()
end)
nnoremap("<leader>dlb", function()
  require("telescope").extensions.dap.list_breakpoints()
end)
