add_newline = false
command_timeout = 600

[line_break]
disabled = true

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold green)"

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[git_branch]
disabled = true

[cmd_duration]
disabled = true
